version: 2.1

jobs:
  build-and-scan:
    machine:  
      image: ubuntu-2004:202010-01  

    steps:
      - checkout

      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v && npm -v  # confirm installation

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Tests
          command: npm test

      - run:
          name: SonarQube Analysis
          command: |
            # Download and unzip SonarQube Scanner
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner.zip
            ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=your_organization \
              -Dsonar.login=$SONAR_TOKEN  # using the token saved in CircleCI environment variables

workflows:
  version: 2
  build-and-scan:
    jobs:
      - build-and-scan
